name: Wallet App

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security scan
        run: |
          echo "Running security check ...1"
          sleep 3s
          echo "Running security check ...2"
          sleep 3s

  build:
    name: Build
    needs: securityCheck
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
